FROM ghcr.io/puppeteer/puppeteer:latest  as base

WORKDIR /usr/app
COPY ./src ./src
COPY ./package.json ./
RUN yarn install


ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG APPLICATION_TOKEN
ARG CRON_SCHEDULE_SEND_MSG
ARG CRON_SCHEDULE_CRAWL

ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT 
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV APPLICATION_TOKEN=$APPLICATION_TOKEN
ENV CRON_SCHEDULE_SEND_MSG=$CRON_SCHEDULE_SEND_MSG
ENV CRON_SCHEDULE_CRAWL=$CRON_SCHEDULE_CRAWL


CMD [ "yarn", "dev" ]
